services:
  - type: web
    name: alonso-ebanisteria
    env: python
    buildCommand: sh build_files.sh
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alonso_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
    buildFilter:
      paths:
        - static/**
        - templates/**
        - myapp/**
        - myproject/**
        - requirements.txt
        - build_files.sh
        - manage.py

databases:
  - name: alonso_db
    plan: free
